Added install.sh script, and optimized the script

diff --git a/klibbert b/klibbert
--- a/klibbert
+++ b/klibbert
@@ -2,30 +2,55 @@
 # Written by Simon Sinding - 2016 Github.com/TheSinding/
 SCREENSHOT_DIR="$HOME/screenshots/"
 SCROT_FILE_OPTIONS="%Y-%m-%d_\$wx\$h_scrot.png"
+hash scrot 2>/dev/null ||
+{
+	echo >&2 "Error: Scrot is required but it's not installed.  Aborting.";
+	exit 1; 
+}
 
+hash pastey 2>/dev/null || 
+{ 
+	echo >&2 "Error: Pastey is required but it's not installed, see https://github.com/TheSinding/pastey/.  Aborting."; 
+	exit 1; 
+}
 if [ ! -d $SCREENSHOT_DIR ]; then
 	echo "Info: $HOME/screenshots/ does not exists, creating it!"
 	mkdir $SCREENSHOT_DIR
 fi
-
-if [ $1 ]; then
-	if [ $1 = '-h' ]; then
+HELP(){
 		echo "Written by Simon Sinding - 2016 - Github.com/TheSinding/"
 		echo "Usage: klibbert [OPTIONS]"
 		echo "	-h, 	Shows this help"
 		echo "	-f,		Fullscreen screenshot"
 		echo "	-r,		Region screenshot"
-	elif [ $1 = '-f' ]; then
-		url=$(scrot $SCREENSHOT_DIR$SCROT_FILE_OPTIONS -e 'pastey -f $f' 2>&1)
-	elif [ $1 = '-r' ]; then
-		url=$(scrot -s $SCREENSHOT_DIR$SCROT_FILE_OPTIONS -e 'pastey -f $f' 2>&1)
-	else
-		echo "$1 is an unknown parameter. See -h for help"
+		exit 1
+}
+OPEN(){
+	if [ $1 ]; then 
+		xdg-open $1
 	fi
-	if [ $url ]; then 
-		xdg-open $url
-	fi
-else
-	echo "You need to add parameters. See -h for help"
-fi
+	exit 1
+}
+while getopts ":frh" opt; do
+  case $opt in
+		h)
+			HELP
+    	;;
+    f)
+			url=$(scrot $SCREENSHOT_DIR$SCROT_FILE_OPTIONS -e 'pastey -f $f' 2>&1)
+			OPEN $url	
+    	;;
+		r)
+			url=$(scrot -s $SCREENSHOT_DIR$SCROT_FILE_OPTIONS -e 'pastey -f $f' 2>&1)
+			OPEN $url	
+			;;
+		\?)
+			echo "Error: -$OPTARG is an invalid option"
+			HELP
+			;;
+  esac
+done
 
+if (($# == 0)); then
+  HELP
+fi
